language: python
sudo: false

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

python:
  - "3.4"

before_install:
  - git clone https://github.com/nsls-ii/nsls2-ci ~/scripts
  - . ~/scripts/install-miniconda.sh

  - git clone https://github.com/NSLS-II/metadataservice.git /home/travis/metadataservice
  - mkdir -p /home/travis/.config/metadataservice
  - mkdir -p /home/travis/.config/metadataclient

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda update conda --yes
  - conda create -n testenv --yes nose python=$TRAVIS_PYTHON_VERSION pymongo ujson numpy tornado jsonschema pyyaml pytz six
  - source activate testenv
  - pip install pytest pytest-cov
  - pip install coveralls codecov
  - pip install tzlocal
  - pip install requests
  - pip install prettytable
  - pip install https://github.com/NSLS-II/metadatastore/zipball/master#egg=metadatastore
  - pip install https://github.com/NSLS-II/doct/zipball/master#egg=doct
  - python setup.py develop
   
script:
  - mkdir -p /home/travis/.config/metadataclient
  - cp connection.yml /home/travis/.config/metadataclient
  - source activate testenv
  - nohup python /home/travis/metadataservice/startup.py --mongohost localhost --mongoport 27017 --serviceport 7778 --database mdservicetest --tzone US/Eastern &
  - sleep 5
  - export PYTHONPATH=$PYTHONPATH:/home/travis/metadataclient
  - py.test -sv --cov=metadataclient --cov-report term-missing
  - cat nohup.out

after_success:
  - coveralls
  - codecov
