language: python
sudo: false

services:
  - mongodb

python:
  - 2.7
  - 3.4

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - export MDS_HOST=localhost
  - export MDS_PORT=27017
  - export MDS_DATABASE=test

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda update conda --yes
  - conda create -n testenv --yes pip nose python=$TRAVIS_PYTHON_VERSION pymongo six pyyaml numpy
  - conda install -n testenv --yes -c nikea mongoengine
  - source activate testenv
  - pip install coveralls
  - python setup.py install


script:
  - python run_tests.py

after_success:
  coveralls
