language: python
sudo: false

services:
  - mongodb

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
  allow_failures:
    - python: 3.5

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - export MDS_HOST=localhost
  - export MDS_DATABASE=test
  - export MDS_TIMEZONE=US/Eastern
  - mkdir -p /home/travis/.config/metadatastore
  - 'echo ''port: 27017'' > /home/travis/.config/metadatastore/connection.yml'

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda config --set always_yes true
  - conda update conda --yes
  - conda create -n testenv pip nose python=$TRAVIS_PYTHON_VERSION pymongo six pyyaml numpy pandas jinja2
  # install deps that will reliably exist on our public anaconda.org build channel
  - conda install -n testenv -c lightsource2 mongoengine boltons prettytable humanize
  # install deps for building a conda package on travis
  - conda install conda-build jinja2
  - source activate testenv
  - pip install coveralls codecov
  - python setup.py install


script:
  - python run_tests.py -v
  - git fetch --unshallow
  # add our public build channel so that conda-build can access any pacakges it needs
  - conda config --add channels lightsource2
  - conda build conda-recipe

after_success:
  - coveralls
  - codecov
