language: python
sudo: false
env:
  global:
    BUILD_DOCS_BRANCH: master
    DOCS_SUBDIR: doc/
    TARGET_DEV_SUBDIR: databroker/
    HTML_SUBDIR: build/html
    DOCS_CONDA_DEPS: "matplotlib"
    DOCS_PIP_DEPS: "tqdm"

services:
  - mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

matrix:
  include:
    - python: 2.7
      env: BUILD_DOCS=false
    - python: 3.4
      env: BUILD_DOCS=false
    - python: 3.5
      env: BUILD_DOCS=true

before_install:
  - git clone https://github.com/nsls-ii/nsls2-ci ~/ci_scripts
  - . ~/ci_scripts/install-miniconda.sh
  - git clone https://github.com/NSLS-II/metadataservice.git /home/travis/metadataservice

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create -n testenv pip pytest python=$TRAVIS_PYTHON_VERSION six numpy pandas h5py coverage jsonschema jinja2 cytoolz pyyaml mongoengine tzlocal boltons pymongo pims tifffile doct channelarchiver pip pytest python=$TRAVIS_PYTHON_VERSION pymongo six pyyaml numpy h5py jsonschema boltons pims tifffile doct nose python=$TRAVIS_PYTHON_VERSION pymongo ujson numpy tornado jsonschema pyyaml pytz six pip pytest python=$TRAVIS_PYTHON_VERSION mongoquery numpy h5py coverage doct six tzlocal
  - source activate testenv
  - conda install --force requests  # hitting some 3.4-only requests bug
  - pip install mongoquery attrs
  - pip install https://github.com/NSLS-II/portable-mds/zipball/master
  - pip install https://github.com/NSLS-II/portable-fs/zipball/master
  - pip install coveralls codecov
  - |
    if [ $TRAVIS_PYTHON_VERSION = "2.7" ]; then
      pip install singledispatch;
      pip install "https://github.com/NSLS-II/metadatastore/zipball/master";
    fi;
  - |
    if [ $TRAVIS_PYTHON_VERSION != "2.7" ]; then
      conda install bluesky;  # Use this to install deps.
      conda remove metadatastore --force;
      conda remove filestore --force;
      conda remove bluesky --force;
      pip install https://github.com/NSLS-II/metadatastore/zipball/master;
      pip install https://github.com/NSLS-II/bluesky/zipball/master;

      fi;

  - pip install https://github.com/NSLS-II/filestore/zipball/master
  - pip install pytest pytest-cov
  - pip install coveralls codecov
  - pip install tzlocal
  - pip install requests
  - pip install prettytable
  - pip install https://github.com/NSLS-II/metadatastore/zipball/master#egg=metadatastore
  - pip install https://github.com/NSLS-II/doct/zipball/master#egg=doct

  - python setup.py install
  # Need to clean the repo or pytest gets confused why there are *two* copies
  # of all the python files
  - git clean -xfd

script:
  - mkdir -p /home/travis/.config/metadataclient
  - cp connection.yml /home/travis/.config/metadataclient
  - source activate testenv
  - nohup python /home/travis/metadataservice/startup.py --mongo-host localhost --mongo-port 27017 --service-port 7778 --database mdservicetest --timezone US/Eastern --auth --mongo-user tom --mongo-pwd jerry &
  - sleep 5
  - export PYTHONPATH=$PYTHONPATH:/home/travis/metadataclient
  - cat nohup.out

  - coverage run run_tests.py
  - |
    if [ $BUILD_DOCS == true ]; then
      source ~/ci_scripts/make-docs.sh
    fi

after_success:
  - codecov
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == 'NSLS-II/databroker' && $BUILD_DOCS == true && $TRAVIS_BRANCH == 'master' ]]; then
      echo "Adding encrypted deployment key for uploading docs"
      openssl aes-256-cbc -K $encrypted_fc5d6c7ff840_key -iv $encrypted_fc5d6c7ff840_iv -in databroker-docs-deploy.enc -out databroker-docs-deploy -d
      eval `ssh-agent -s`
      chmod 600 databroker-docs-deploy
      ssh-add databroker-docs-deploy
      source ~/ci_scripts/push-docs.sh
    fi
