language: python
sudo: false

services:
  - mongodb

python:
  - 3.5

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - export PATH=/home/travis/mc/bin:$PATH
  - mkdir -p /home/travis/.config/metadataservice
  - mkdir -p /home/travis/.config/metadataclient
  - 'echo ''timezone: US/Eastern'' >> /home/travis/.config/metadataservice/connection.yml'
  - 'echo ''port: 7770'' > /home/travis/.config/metadataclient/connection.yml'
  - 'echo ''host: localhost'' >> /home/travis/.config/metadataclient/connection.yml'
  - 'echo ''protocol: http'' >> /home/travis/.config/metadataclient/connection.yml'
  - 'echo ''timezone: US/Eastern'' >> /home/travis/.config/metadataclient/connection.yml'

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda update conda --yes
  - conda create -n testenv --yes nose python=$TRAVIS_PYTHON_VERSION pymongo ujson numpy tornado jsonschema requests pyyaml pytz six
  - source activate testenv
  - pip install coveralls codecov
  - pip install prettytable
  - 'pip install https://github.com/NSLS-II/doct/zipball/master#egg=doct'
  - 'pip install https://github.com/tacaswell/metadataservice-1/zipball/enh_add_entrypoint#egg=metadataservice'
  - python setup.py install

script:
  - python run_tests.py -v

after_success:
  - coveralls
  - codecov
