language: python

sudo: required 

services:
    - mongodb

addons:
  apt:
    sources:
    - mongodb-3.2-precise 
    packages:
    - mongodb-org

python:
  - 2.7
  - 3.4
  - 3.5

before_install:
  - git clone https://github.com/arkilic/nsls2-ci ~/scripts
  - . ~/scripts/install-miniconda.sh
  - . ~/scripts/init-metadatastore.sh
  

install:
  - mongo localhost:27017/admin ~/scripts/admin.js
  - conda create -n testenv pip pytest python=$TRAVIS_PYTHON_VERSION pymongo six pyyaml numpy pandas jinja2 humanize doct
  - source activate testenv
  - pip install codecov
  - python setup.py install
  - git clean -xfd
  - python -c "import metadatastore; print(metadatastore.__version__)"

script:
  - coverage run run_tests.py
  - coverage report -m

after_success:
- codecov
