package:
  name: filestore
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'GIT_STUB')[1:] }}.post{{ environ.get('GIT_DESCRIBE_NUMBER', 'inf') }}

source:
  git_url: ../
  patches:
    - config.patch

build:
  number: 1

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}


requirements:
  build:
    - python
    - six

  run:
    - python
    - h5py
    - numpy
    - six
    - pyyaml
    - jsonschema
    - pims
    - boltons
    - pymongo
    - doct

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - filestore
    - filestore.api
    - filestore.commands
    - filestore.conf
    - filestore.core
    - filestore.file_writers
    - filestore.fs
    - filestore.handlers_base
    - filestore.handlers
    - filestore.path_only_handlers
    - filestore.retrieve
    - filestore.readers
    - filestore.readers.spe

about:
  home: https://github.com/NSLS-II/filestore
  license: BSD
