package:
  name: databroker
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

build:
  number: 0

  # Note that this will override the default build string with the Python
  #   # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}

requirements:
  build:
    - python
    - numpy
    - six

  run:
    - python
    - pandas
    - pyyaml
    - pims
    - metadatastore >=0.2.0
    - filestore >=0.2.0
    - channelarchiver
    - six
    - humanize
    - tzlocal

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - databroker
    - databroker.testing
    - databroker.examples
    - databroker.examples.sample_data
    - databroker.utils

about:
  home: https://github.com/NSLS-II/databroker
  license: BSD
