package:
  name: dataportal 
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

build:
  number: 0

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_np{{ np }}py{{ py }}

  entry_points:
    - replay = dataportal.replay.run:main

requirements:
  build:
    - python
    - enaml
    - numpy
    - six

  run:
    - python
    - pandas
    - matplotlib
    - pyyaml
    - enaml
    - bubblegum
    - scikit-xray
    - pims
    - metadatastore
    - filestore
    - channelarchiver

test:
  imports:
    - dataportal.broker
    - dataportal.replay
