package:
  name: dataportal
  version: v0.2.2

source:
  git_url: ../

build:
  number: 0

  # Note that this will override the default build string with the Python
  #   # and NumPy versions
  string: v0.2.2

requirements:
  build:
    - python
    - numpy
    - six

  run:
    - python
    - pandas
    - pyyaml
    - pims
    - metadatastore >=0.2.0
    - filestore >=0.2.0
    - channelarchiver
    - six
    - humanize
    - tzlocal

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - dataportal
    - dataportal.api
    - dataportal.testing
    - dataportal.examples
    - dataportal.examples.sample_data
    - dataportal.broker
    - dataportal.muxer
    - dataportal.sources
    - dataportal.sources.dummy_sources
    - dataportal.utils

about:
  home: https://github.com/NSLS-II/dataportal
  license: BSD
